version: '3.9'

services:
  musicat:
    image: ghcr.io/lukacsi/musicat:latest
    stdin_open: true
    tty: true
    user: "${PUID:-1000}:${PGID:-1000}"
    environment:
      # in case your entrypoint or bot reads these
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    memswap_limit: 512M
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    volumes:
      - ./exe/sha_conf.docker.json:/home/musicat/sha_conf.json:ro
      #- ./music:/home/musicat/music
    networks:
      - default

  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_USER: musicat
      POSTGRES_PASSWORD: musicat
      POSTGRES_DB: musicat
    volumes:
      - musicat-pg:/var/lib/postgresql/data
    networks:
      - default

volumes:
  musicat-pg:

networks:
  default:
